const mongoose=require('mongoose')

const Template=new mongoose.Schema({
            userID:{
                type:String,
                required:false
            },
            tempid:{
                type:String,
                required:false
            },
            firstName:{
                type:String,
                required:false              
            },
            lastName:{
                type:String,
                required:false              
            },
            email:{
                type:String,
                required:false              
            },
            mobile:{
                type:String,
                required:false              
            },
            linkedIn:{
                type:String,
                required:false              
            },
            github:{
                type:String,
                required:false              
            },
            lastName:{
                type:String,
                required:false              
            },
            University_or_SchoolName:{
                type:String,
                required:false              
            },
            MajorSubject:{
                type:String,
                required:false              
            },
            qualification:{
                type:String,
                required:false              
            },
            passingYear:{
                type:String,
                required:false              
            },
            Percentage:{
                type:String,
                required:false              
            },
            companyName:{
                type:String,
                required:false              
            },
            Position:{
                type:String,
                required:false              
            },
            Start_Date:{
                type:String,
                required:false              
            },
            End_Date:{
                type:String,
                required:false              
            },
            Description:{
                type:String,
                required:false              
            },
            ProjectTitle:{
                type:String,
                required:false              
            },
            ProjectLink:{
                type:String,
                required:false              
            },
            ProDescription:{
                type:String,
                required:false              
            },
            Skill:{
                type:String,
                required:false              
            },
            language:{
                type:String,
                required:false              
            },
            Certification:{
                type:String,
                required:false              
            },
            achievements:{
                type:String,
                required:false              
            },
            seminar:{
                type:String,
                required:false              
            },
            hobbies:{
                type:String,
                required:false
            }
        
})
const Templates=mongoose.model('usertemplate',Template)
module.exports=Templates